insert into Language (id, name) values (0, 'es-ES');
http://ep00.epimg.net/rss/elpais/portada.xml
http://ep00.epimg.net/rss/cat/portada.xml
http://ep00.epimg.net/rss/elpais/portada_america.xml
http://ep00.epimg.net/rss/brasil/portada.xml
http://ep00.epimg.net/rss/tags/ultimas_noticias.xml
http://ep00.epimg.net/rss/tags/noticias_mas_vistas.xml
http://ep00.epimg.net/rss/internacional/portada.xml
http://elpais.com/tag/rss/latinoamerica/a/
http://elpais.com/tag/rss/mexico/a/
http://elpais.com/tag/rss/europa/a/
http://elpais.com/tag/rss/estados_unidos/a/
http://elpais.com/tag/rss/oriente_proximo/a/
http://ep00.epimg.net/rss/elpais/opinion.xml
http://ep00.epimg.net/rss/politica/portada.xml
http://ep00.epimg.net/rss/ccaa/andalucia.xml
http://ep00.epimg.net/rss/ccaa/catalunya.xml
http://ep00.epimg.net/rss/ccaa/valencia.xml
http://ep00.epimg.net/rss/ccaa/madrid.xml
http://ep00.epimg.net/rss/ccaa/paisvasco.xml
http://ep00.epimg.net/rss/ccaa/galicia.xml
http://ep00.epimg.net/rss/economia/portada.xml
http://ep00.epimg.net/rss/elpais/ciencia.xml
http://ep00.epimg.net/rss/cultura/portada.xml
http://elpais.com/tag/rss/libros/a/
http://elpais.com/tag/rss/cine/a/
http://elpais.com/tag/rss/musica/a/
http://elpais.com/tag/rss/teatro/a/
http://elpais.com/tag/rss/danza/a/
http://elpais.com/tag/rss/arquitectura/a/
http://elpais.com/tag/rss/toros/a/
http://ep00.epimg.net/rss/elpais/estilo.xml
http://ep00.epimg.net/rss/deportes/portada.xml
http://elpais.com/tag/rss/futbol/a/
http://elpais.com/tag/rss/deportes_motor/a/
http://elpais.com/tag/rss/baloncesto/a/
http://elpais.com/tag/rss/ciclismo/a/
http://elpais.com/tag/rss/tenis/a/
http://ep00.epimg.net/rss/cultura/television.xml
http://ep00.epimg.net/rss/sociedad/portada.xml
http://elpais.com/tag/rss/gente/a/
http://elpais.com/tag/rss/religion/a/
http://elpais.com/tag/rss/educacion/a/
http://elpais.com/tag/rss/salud/a
http://www.elpais.com/rss/feed.html?feedId=17187
http://ep00.epimg.net/rss/elpais/entrevistasdigitales.xml
http://estaticos.elmundo.es/elmundo/rss/portada.xml
http://estaticos.elmundo.es/elmundo/rss/espana.xml
http://estaticos.elmundo.es/elmundo/rss/internacional.xml
http://estaticos.elmundo.es/elmundo/rss/union_europea.xml
http://estaticos.elmundo.es/elmundo/rss/economia.xml
http://estaticos.elmundo.es/elmundo/rss/cultura.xml
http://estaticos.elmundo.es/elmundo/rss/ciencia.xml
http://estaticos.elmundo.es/elmundo/rss/madrid.xml
http://estaticos.elmundo.es/elmundo/rss/barcelona.xml
http://estaticos.elmundo.es/elmundo/rss/baleares.xml
http://estaticos.elmundo.es/elmundo/rss/castillayleon.xml
http://estaticos.elmundo.es/elmundo/rss/valladolid.xml
http://estaticos.elmundo.es/elmundo/rss/valencia.xml
http://estaticos.elmundo.es/elmundo/rss/alicante.xml
http://estaticos.elmundo.es/elmundo/rss/castellon.xml
http://estaticos.elmundo.es/elmundo/rss/paisvasco.xml
http://estaticos.elmundo.es/elmundo/rss/andalucia.xml
http://estaticos.elmundo.es/elmundo/rss/andalucia_sevilla.xml
http://estaticos.elmundo.es/elmundo/rss/andalucia_malaga.xml
http://estaticos.elmundo.es/elmundo/rss/solidaridad.xml
http://estaticos.elmundo.es/elmundo/rss/comunicacion.xml
http://estaticos.elmundo.es/elmundo/rss/television.xml
http://estaticos.elmundo.es/elmundo/rss/suvivienda.xml
http://estaticos.elmundo.es/elmundo/rss/navegante.xml
http://estaticos.elmundo.es/blogs/elmundo/el-gadgetoblog/index.xml
http://estaticos.elmundo.es/blogs/elmundo/catalejo/index.xml
http://estaticos.elmundo.es/blogs/elmundo/mundoplayer/index.xml
http://estaticos.elmundo.es/blogs/elmundo/abogado_navegante/index.xml
http://estaticos.elmundo.es/blogs/elmundo/aypad/index.xml
http://estaticos.elmundo.es/elmundodeporte/rss/portada.xml
http://estaticos.elmundo.es/elmundodeporte/rss/futbol.xml
http://estaticos.elmundo.es/elmundodeporte/rss/baloncesto.xml
http://estaticos.elmundo.es/elmundodeporte/rss/ciclismo.xml
http://estaticos.elmundo.es/elmundodeporte/rss/golf.xml
http://estaticos.elmundo.es/elmundodeporte/rss/tenis.xml
http://estaticos.elmundo.es/elmundodeporte/rss/motor.xml
http://estaticos.elmundo.es/elmundodeporte/rss/masdeporte.xml
http://estaticos.elmundo.es/elmundosalud/rss/portada.xml
http://estaticos.elmundo.es/elmundomotor/rss/portada.xml
http://rss.elmundo.es/rss/descarga.htm?data2=15
http://estaticos.elmundo.es/yodona/rss/portada.xml
http://estaticos.elmundo.es/yodona/rss/blogs/cuentahilos.xml
http://estaticos.elmundo.es/yodona/rss/blogs/modamania.xml
http://estaticos.elmundo.es/yodona/rss/blogs/grandclass.xml
http://estaticos.elmundo.es/elmundo/rss/blogs/palabrasarchivadas.xml
http://estaticos.elmundo.es/blogs/elmundo/consejoeditorial/index.xml
